### ISSUE TITLE
Document the registration procedure

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc#103]
Subject says all.

**Comment by ashutosh3308** [comment]
I am using realsense to do the point cloud registration. Here are the issues that I faced. 

- The `realsense viewer` software was installed already, but the version was wrong. The version needs to be adapted according to `cwipc`. `Version v2.54.2` is right and can be downloaded from [this](https://github.com/IntelRealSense/librealsense/releases ) link. 
- To create `Cameraconfig`, I used the `CWIPC_register` command to create the `cameraconfig` file.
- I discussed with Jack to do the calibration, we used command `cwipc_register` --rgb. This command can create `cameraconfig` file and do the `registration` process as well.

**Comment by jackjansen** [comment]
I'm getting started on the registration documentation. @ashutosh3308 let's add some images and such on Monday.

**Comment by jackjansen** [comment]
Fixed in 7.5.3
