### ISSUE TITLE
Add functionality to scripts to allow converting 8i datasets

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc#13]
Currently we convert the 8i dataset with a specialised script from `cwipc_test`, but it would be good if we could do this with a utility. Possibly `cwipc_grab`, but that may be overloading too much functionality into one tool, maybe a `cwipc_convert` tool?

It would need:

- argument to set FPS (so we can convert sequence numbers to timestamps,
- argument(s) to determine scaling, translation, rotation (maybe one argument to specify a 4x4 matrix? maybe `cameraconfig`-style?),
- arguments to determine tiling (maybe simply N tiles?)

Another option is that we add a `--standard-filter filtername`, and somewhere have predefined filters (in `share/cwipc/filters`). `--spatial_crop` could then be such a standard filter too.

**Comment by jackjansen** [comment]
Assigning to @nachoreimat for feedback.

**Comment by nachoreimat** [comment]
I guess that is something totally dependent on the usecase. I remember we implemented the customfilter option, which I guess could be use for this type of costumizations.

Apart from that, I agree that having a `cwipc_convert` to not oversaturate `cwipc_grab` may be a good idea :)

**Comment by jackjansen** [comment]
#53 should solve this.
