### ISSUE TITLE
Upgrade to Python 3.9 when Open3D is ready

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc#2]
At the moment we're stuck at Python 3.8, because Open3D hasn't been released for 3.9 on PyPi yet.

Track https://github.com/isl-org/Open3D/issues/3805 and move to 3.9 when done.

**Comment by jackjansen** [comment]
There's a very valid comment over in the Open3D issue, about creating a repo specifically to store external distributions. Check it.

**Comment by cclauss** [comment]
This should be ready to go.

**Comment by jackjansen** [comment]
Tried to build with Python 3.9, but unfortunately still no go: PyPi version of Open3D is still at 0.13:-(

Try again next week or so (there's no open3d issue that can be tracked: both the one referenced above and https://github.com/isl-org/Open3D/issues/3983 have been closed by the open3D people).

**Comment by cclauss** [comment]
Python 3.10 will be released in a week or so (Oct. 4th).

https://github.com/actions/python-versions/releases

https://www.python.org/downloads/release/python-3100rc2

**Comment by jackjansen** [comment]
@cclauss yes, I am very aware of that:-) And if Open3D comes out for 3.10 I'll jump for that straight away. But for the `cwipc` project the first hurdle is getting away from 3.8, which is now almost 2 years old and in security-fix mode....

**Comment by jackjansen** [comment]
We're at Python 3.9. Not yet 3.10, but that'll have to wait, because again open3d is laging.
