### ISSUE TITLE
Issues while building for windows

### ISSUE THREAD

**Issue by AR-Vsx** [cwi-dis/cwipc#4]
I finally got the build runing but I ran into some issues during the build process.

- Had to install the 64-bit versions of pcl and boost via vcpkg
- Had to install OpenCV
- Had to add `#pragma comment(lib, "Ws2_32.lib")` to `cwipc_proxy.cpp` in cwipc_util because it wasn't linked for some reason
- In order to successfully complete the tests I had to copy  `k4a.dll k4abt.dll k4arecord depthengine_2_0.dll` from the Kinect SDK and Body Tracking SDK into the `build/bin/RelWithDebInfo` folder and I had to rename `lz4.dll` to `lz4d.dll`

Just wanted to give a heads up if somebody else is also running into these issues.

**Comment by jackjansen** [comment]
Thank you! I'm completely revamping the build process (on branch issue15-github-actions). I had come across your first three bullets already, but solved them in a slightly different way. I'll keep my eye open for the lz4.dll issue.

The branch should be merged in another few days, I'll let you know.

**Comment by jackjansen** [comment]
There is a new release v7.2, https://github.com/cwi-dis/cwipc/releases/tag/v7.2

It is probably best to uninstall all remains of previous attempts before installing this.

I'm reasonably sure it should address the issues here. Please reopen this issue (with details) if that is not the case.
