### ISSUE TITLE
k4aoffline : No support for Kinect offline grabber on this platform

### ISSUE THREAD

**Issue by ashutosh3308** [cwi-dis/cwipc#44]
Tested on **Windows 11**, CWIPC: **v7.4.3**

**Command Used:** cwipc_grab --k4aoffline --binary --fpattern timestamp:08d --inpoint 5727933 --outpoint 36561266 --nodrop --outliers 30 1.1 1 ply

**Comment by cwidisgroup** [comment]
@ashutosh3308 I have completely forgotten what this issue is about, and the report doesn't help me miuch either.

Does this issue still exist? If so: can you give me a more extended recipe on how to see it? I.e. which data should I run this command on, etc...

After that please assign back to me.
