### ISSUE TITLE
cwipc_kinect() crashes when passed an XML configfile.

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/cwipc#55]
Subject says all. Seen in Unity on Windows.

**Comment by cwidisgroup** [comment]
The problem may be slightly different: it may be that it crashes when given a nonexistent filename.

**Comment by jackjansen** [comment]
It turned out to be different again: the various capturers crashed if passed an _empty_ string as the config filename. This tended to happen only in our Unity projects.
