### ISSUE TITLE
Issues with Windows installer and Python

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/cwipc#98]
There are two more issues with the Windows installer and the Python scripts:

- The installer doesn't install the scripts (like `cwipc_view`) correctly if Python has been installed the standard way (i.e. in `Program Files`). It works correctly if Python has been installed to `C:/python`.
- Even if you then run the cwipc install fixer things don't work: `pip` will install the scripts into `~/AppData` somewhere, but this isn't on `PATH`.

**Comment by cwidisgroup** [comment]
The workaround _may_ be to ensure the `pip` command is run with Administrator privileges.

**Comment by jackjansen** [comment]
That worked. Python packages are now installed during `install-third-party-packages-full`, as administrator, so the cwipc packages and the scripts end up in the Python application folder.
